server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/x-protobuf
    min-response-size: 1024

spring:
  application:
    name: test-publish-data-protos-webflux
